version: '2.0'

services:
    php-fpm:
        build: .docker/php-fpm
        volumes:
            - ./src:/var/www/
        networks:
            - balda
        restart: always

    nginx:
        build: .docker/nginx
        environment:
            APP_ENV: ${APP_ENV}
        volumes:
            - ./src:/var/www
        networks:
            - balda
        ports:
            - '${DOCKER}:80:80'
        links:
            - php-fpm
        restart: always

    mercure:
        container_name: mercure
        image: dunglas/mercure
        environment:
            # You should definitely change all these values in production
            - JWT_KEY=YourSecretKey
            - DEMO=1
            - ALLOW_ANONYMOUS=1
            - HEARTBEAT_INTERVAL=30s
            - ADDR=:3000
            - CORS_ALLOWED_ORIGINS=http://10.10.101.1
            - PUBLISH_ALLOWED_ORIGINS=http://10.10.101.1
        ports:
            - "${DOCKER}:3000:3000"
        restart: always
        networks:
            - balda

networks:
    balda:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK}